development: &my_settings
  enable_star: true
  min_infix_len: 1
  charset_type: utf-8
  morphology: 'stem_en, stem_ru'
  charset_table: '0..9, A..Z->a..z, _, @, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+451, U+22, U+25..U+27'
  sql_user: 'postgres'
  use_64_bit: true
  collation_server: utf8_ci
test:
  <<: *my_settings
  port: 9313
production:
  <<: *my_settings
  port: 9312
development:
  <<: *my_settings
  port: 9312

