development: &my_settings
  port: 9333
  enable_star: true
  min_infix_len: 1
  charset_type: utf-8
  morphology: 'stem_en, stem_ru'
  charset_table: "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+458, U+0022, U+0026, U+0027, U+42F, U+44F, U+043B, U+041B, U+0456, U+0457, U+0406, U+0407, U+400..U+4FF"
test:
  <<: *my_settings
production:
  <<: *my_settings
  bin_path: '/usr/local/bin'
